[package]
name = "integration"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = { version = "0.14.6", features = ["transport",'tls-ring'] }
prost = "0.14.4"
tonic-prost = "0.14.6"
tonic-reflection = "0.14.6"
tower = "0.5.3"
tokio = { workspace = true}
dotenvy = {workspace = true}
tracing-subscriber = {workspace = true}

business = { path = "../business" }
chrono = { version = "0.4.45", features = ["serde"] }
hyper = "1.11.0"
log = "0.4.33"
rustls = "0.23.40"
uuid = { workspace = true }


[dependencies.sea-orm]
version = "2.0.1"
features = [
    "runtime-tokio-native-tls",
    "sqlx-postgres",
    "with-uuid",
    "with-chrono"
]

[build-dependencies]
tonic-prost-build = "0.14.6"
protoc-bin-vendored = "3.2.0"
