apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo
  labels:
    {{- include "socialgym.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.mongo.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.mongo.storage }}
