apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    {{- include "socialgym.labels" . | nindent 4 }}
spec:
  selector:
    app: mongo
  ports:
    - name: mongo
      port: {{ .Values.mongo.port }}
      targetPort: mongo
