apiVersion: v1
kind: Service
metadata:
  name: workout
  labels:
    {{- include "socialgym.labels" . | nindent 4 }}
spec:
  selector:
    app: workout
  ports:
    - name: http
      port: {{ .Values.workout.port }}
      targetPort: http
