apiVersion: v1
kind: Secret
metadata:
  name: cloudfront-key
  namespace: workout-app
type: Opaque
stringData:
  cloudfront_private_rsa.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDNQ7f/iMrvUoZH
    Swrv1Gm9d+bqf9sCgQzl0JCagHlXdLjD0tsxc8gM0QkOb1lAmLqHpIMCw4k2qSRq
    9IzaFucBXnjmsbzOdTXnF87zRTm+CFMepUPIRFZX1OZWBW0yFIPnLltcfhNxzrS5
    CiVlTjVQ8vue3vJ7F6HH/IJS4WAA58erSvuHPGFQo9XANzNdcgtfI7sT1Hw9fv0G
    YhoDr1YPXk3rb4R/RYBwlt+WmHEEkCMDvI5zPCBDTiBxMYUHauuCwldyiLaujAzc
    B6jqqVNsEloSR9qXFc8JtTYJRL4on0zKlt54Kixn1n0TZInnpw/E3PlYdzLhlpCB
    juY4zla9AgMBAAECggEAEZzvc2pR+4IpyoFKcXTZE+xvcIzDBq57JFcmqVM/1jzK
    Q+dabp5gOpVPQSFV18CjNNNteHW91uZhnRnZ4jbX4JqyJh13NYICO4+j7uTwRPmi
    5DzLGaqffA7lKtlxWrw+6z3jkgaxdXEGueAAgHZbBdSruaCozt4iwC3PIvx6x+j0
    MZj+7UPyUnrI6ZrJyhqVCWnQrK8AVOx4/IuaIeBTpHT9YY7H7JolRBTozQ5Qgbmg
    JuKDwR3p0oJfoOI5CbTTyIHnXWBDWogbdzZMYbESncMj2JXkdwTxv4pp2LHrQg1g
    toiEYG7rAVkHMd0X36GLDwUubKM9oavvW9gLkTX74wKBgQDslPKaDQLApxm4jmBN
    s1oFRNrpznWIIbXJeEJh72aCknqf2Y1A5nzW8PYUGJ5AMmJzbZPLFsJaVunqHoom
    LykHYRq+L9JYn0AGk7KF02iR+eugDUYtvcLRAqAUb3Ff2TDGn5LoP+xpk0W1n9cg
    kir+0qHsJh6u3j+TwmlwtuCfAwKBgQDeHLuNU8ODdmOm3K3XCJsf2KWLWOpG2bfF
    I0EIs6+d5OGX4AdMTA0cwMliW5RIuArGcFJjR0bnV0s8hmulxfC/FUOLXP8I6vig
    Re46PWdMwSsAOplste8aI5KfCQbhTgOrQDIx23857gjGxgEwZZqJDnG0aWvfofCU
    07/94i9nPwKBgQCqxf21G80v2a8kXInBrMQ/Z2uKOED4yjSZwJhSb2gUur2PY4+m
    GHpnATrwWLDq8DPG1INJpx0V7wUcvXzFgWdhb0PJo2V4GUQzOywzk944+SmPt+U/
    oWneS8HX3nX9VR7zUT7PLU1vDCLWrxGv7jLhDJRbjUy6t6028LAB79CGlwKBgBTE
    uwTMAEwaldbUa6zfsSGZMGGHPuDBGt3kHgCiTJmG/VEmMYiA0/kMTchUp9jk3J0R
    g6Kk14xqLS7LouUtTQWRB2/QkkhTMExMPapUc4RJy6uJzy7LFEBtcxhLz8jhcpZg
    ulDPJWZVS5zKhvHvjjOilh84fE285rID2r/yllwhAoGATCl0dmPVbDlnCJSx3JrA
    NsVe/gSCP9qX8xY2GalLn35b9wTj/4IJRT7MGvITQWoXuNpKLE9V9enAvPUGWFXn
    04Rgw7+8BAD4g85zYNt9BW8d3ZAJS9N7KG6B3QoYNEBql6Iei1bQLgvvI4SwUQbM
    kfcjm/3YGFmAmEKWs/h9oSQ=
    -----END PRIVATE KEY-----

