apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: workout-app

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - cloudfront-secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml

commonLabels:
  app.kubernetes.io/name: workout-app
  app.kubernetes.io/version: v1

commonAnnotations:
  managed-by: "kustomize"
  environment: "production"

