apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    {{- include "socialgym.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gateway.serviceType }}
  selector:
    app: gateway
  ports:
    - name: http
      port: {{ .Values.gateway.httpPort }}
      targetPort: http
    - name: https
      port: {{ .Values.gateway.httpsPort }}
      targetPort: https
