//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use chrono::{NaiveDate, Utc};
use sea_orm::entity::prelude::*;
use sea_orm::prelude::async_trait::async_trait;
use sea_orm::Set;

pub type PersonEntity = Model;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "person")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,

    #[sea_orm(unique)]
    pub uuid: Uuid,
    pub first_name: String,
    pub surname: String,
    pub date_of_birth: NaiveDate,
    pub gender: String,
    pub avatar: Option<String>,
    pub cover_image: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::user_entity::Entity")]
    User,
    #[sea_orm(has_many = "super::workout_entity::Entity")]
    Workout,
    #[sea_orm(has_many = "super::person_address_entity::Entity")]
    PersonAddress,
    #[sea_orm(has_many = "super::profile_entity::Entity")]
    Profile,
}

impl Related<super::user_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::workout_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workout.def()
    }
}

impl Related<super::person_address_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PersonAddress.def()
    }
}

impl Related<super::profile_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Profile.def()
    }
}

#[async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(mut self, _db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        if insert {
            self.uuid = Set(Uuid::new_v4());
            self.created_at = Set(Utc::now());
        }
        self.updated_at = Set(Utc::now());
        Ok(self)
    }
}
