//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

pub use super::person::Entity as Person;
pub use super::person_address::Entity as PersonAddress;
pub use super::person_info::Entity as PersonInfo;
pub use super::user::Entity as User;

pub use super::friends::Entity as Friends;

pub use super::exercise::Entity as Exercise;
pub use super::workout::Entity as Workout;
pub use super::workout_exercise::Entity as WorkoutExercise;

pub use super::business_profile::Entity as BusinessProfile;
pub use super::business_profile_address::Entity as BusinessProfileAddress;

pub use super::person_media::Entity as PersonMedia;
pub use super::country::Entity as Country;

pub use super::settings::Entity as Settings;

pub use super::profile::Entity as Profile;

pub use super::team_member::Entity as TeamMember;

pub use super::revoked_token::Entity as RevokedToken;


