[package]
name = "application"
version = "0.1.0"
edition = "2024"

[dependencies]
business = { path = "../business" }
domain = { path = "../domain" }

dotenvy = {workspace = true}
mongodb = { workspace = true}
tokio = {workspace = true}
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures = "0.3.31"
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
uuid = { workspace = true }

axum = { version = "0.8.9", features = ["ws"] }
tracing-subscriber = "0.3.23"
anyhow = "1.0.102"
log = "0.4.29"
tower-http = { version = "0.6.10", features = ["full"] }
fluent-templates = "0.14.0"
unic-langid = { version = "0.9", features = ["macros"] }





#[[test]]
#name = "mock"
#required-features = ["mock"]
